//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class PlanetWroxEntities : DbContext
{
    public PlanetWroxEntities()
        : base("name=PlanetWroxEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Genre> Genres { get; set; }
    public virtual DbSet<Review> Reviews { get; set; }
    public virtual DbSet<photoalbum> photoalbums { get; set; }
    public virtual DbSet<Picture> Pictures { get; set; }
}
